import type { Content } from "./types"

export const de: Content = {
  nav: {
    home: "Start",
    about: "Über mich",
    experience: "Werdegang",
    projects: "Projekte",
    teaching: "Lehre",
    contact: "Kontakt",
  },
  hero: {
    eyebrow: "Software Engineer · Agile Coach",
    name: "Aniruddh Zaveri",
    tagline:
      "Ich unterrichte Software Engineering und DevOps an der TUM und arbeite gerne mit LLMs, EdTech und datengetriebenen Systemen.",
    workProfileCta: "Arbeitsprofil",
    statusBadge: "M.Sc. Wirtschaftsinformatik @ TUM",
  },
  about: {
    heading: "Über mich",
    body: "Ich studiere Wirtschaftsinformatik an der Technischen Universität München und arbeite als Software Engineer in der Forschungsgruppe Applied Education Technologies. Ich leite den agilen Prozess hinter TUMApply, habe Bachelorarbeiten betreut und unterrichte Kurse von Einführung in die Programmierung bis DevOps. Mich begeistert die Schnittstelle zwischen Management und Informatik. In meiner Freizeit findet man mich beim Teamsport wie Hockey oder beim Gaming.",
    interestsHeading: "Interessen",
    interests: [
      "LLMs & KI-Anwendungen",
      "Educational Technology",
      "Datengetriebene Systeme",
      "Automobilindustrie",
      "Agiles Projektmanagement",
    ],
    languagesHeading: "Sprachen",
    languages: [
      { name: "Deutsch", level: "Muttersprache" },
      { name: "Englisch", level: "Muttersprache" },
      { name: "Hindi", level: "Fließend" },
      { name: "Französisch", level: "Grundkenntnisse" },
    ],
  },
  skills: {
    heading: "Technologien",
    items: [
      "Java",
      "TypeScript",
      "Angular",
      "React",
      "Python",
      "Spring Boot",
      "Spring AI",
      "LangChain",
      "SQL",
      "Docker",
      "CI/CD",
      "AspectJ",
      "Git & GitHub",
      "Agile / Scrum",
      "Softwarearchitektur",
    ],
  },
  experience: {
    heading: "Werdegang",
    sub: "Mein Weg bis heute — Neuestes zuerst.",
    typeLabels: { work: "Arbeit", education: "Ausbildung" },
    entries: [
      {
        id: "nexus-thesis",
        year: 2026,
        period: "Jun 2026 – Dez 2026",
        title: "Masterarbeit — Project Nexus",
        org: "Technische Universität München · BMW",
        location: "München",
        description:
          "KI-gestütztes Technologie-Foresight-System in Zusammenarbeit mit BMW: Trendsignale werden zu wahrscheinlichkeitsgewichteten Zukunftsszenarien. Vollverantwortlich für die interaktive Visualisierung auf dem Touch-Display des BMW Future Lab.",
        tags: ["AI", "Data Visualization", "Touch UI", "React", "Python", "DevOps"],
        type: "education",
      },
      {
        id: "tum-pm",
        year: 2025,
        period: "Feb 2025 – heute",
        title: "Projektmanagement & Systemadministration",
        org: "TU München · Applied Education Technologies",
        location: "München",
        description:
          "Digitalisierung des Promotions-Bewerbungsprozesses der TUM mit TUMApply. Agile Coach für ein Team von 6 Entwicklern, Serveradministration, Entwicklung und Betreuung von Bachelorarbeiten.",
        tags: ["Agile", "Java", "Angular", "Server Admin", "DevOps", "Mentoring"],
        type: "work",
      },
      {
        id: "msc",
        year: 2025,
        period: "2025 – 2027 (voraussichtlich)",
        title: "M.Sc. Wirtschaftsinformatik",
        org: "TU München",
        description:
          "Masterstudium an der Schnittstelle von Software Engineering, Daten und Wirtschaft.",
        tags: [],
        type: "education",
      },
      {
        id: "tum-tutor",
        year: 2024,
        period: "Feb 2024 – Sep 2026 (voraussichtlich)",
        title: "Tutor & Instructor",
        org: "TU München",
        description:
          "Tutor für Einführung in die Softwaretechnik, Einführung in die Programmierung, DevOps und Patterns in Software Engineering.",
        tags: ["Lehre", "Java", "DevOps"],
        type: "work",
      },
      {
        id: "bcg",
        year: 2022,
        period: "Mär 2022 – Feb 2024",
        title: "IT Werkstudent",
        org: "Boston Consulting Group",
        location: "München",
        description:
          "IT-Service-Management, Prozessoptimierung, IT-Trainings und Support, Konferenzvorträge, Programmierung und agile Arbeitsmethoden.",
        tags: ["ITSM", "Prozessoptimierung", "Trainings"],
        type: "work",
      },
      {
        id: "ise",
        year: 2022,
        period: "Apr 2022 – Aug 2022",
        title: "Instructor — Einführung in die Softwaretechnik",
        org: "TU München",
        description:
          "Vorlesungsbetreuung, Erstellung von Übungen, Koordination der Tutorien und Klausurunterstützung.",
        tags: ["Lehre"],
        type: "work",
      },
      {
        id: "bsc",
        year: 2020,
        period: "2020 – 2025",
        title: "B.Sc. Wirtschaftsinformatik",
        org: "TU München",
        description:
          "Bachelorarbeit: Visualization of Test Case Errors — Enhancing Autograding Feedback (entwickelt in Artemis).",
        tags: [],
        type: "education",
      },
      {
        id: "head-tutor",
        year: 2020,
        period: "Okt 2020 – Feb 2021",
        title: "Head Tutor — Einführung in die Programmierung",
        org: "TU München",
        description:
          "Koordination der Tutoren und Unterstützung der Studierenden in einem der größten Programmierkurse der TUM.",
        tags: ["Lehre"],
        type: "work",
      },
      {
        id: "telis",
        year: 2020,
        period: "Aug 2020 – Dez 2020",
        title: "Beratung / Finanzanalyse",
        org: "TELIS FINANZ AG",
        description:
          "Nach einer kurzen Schulung für die Rolle als Finanzberater tätig.",
        tags: ["Beratung"],
        type: "work",
      },
      {
        id: "bmw",
        year: 2017,
        period: "Sep 2017 – Okt 2017",
        title: "Schülerpraktikum — International Accounting",
        org: "BMW Group",
        location: "München",
        description:
          "Teil der Abteilung International Accounting (FR-25) mit Einblicken in die Finanzprozesse eines globalen Automobilkonzerns.",
        tags: ["Finanzen"],
        type: "work",
      },
      {
        id: "abitur",
        year: 2012,
        period: "2012 – 2020",
        title: "Hans-Leinberger-Gymnasium",
        org: "Abitur",
        location: "Landshut",
        description:
          "Allgemeine Hochschulreife 2020 und Mittlerer Schulabschluss 2018.",
        tags: [],
        type: "education",
      },
      {
        id: "colham",
        year: 2010,
        period: "2010 – 2012",
        title: "Colham Manor Primary School",
        org: "Grundschulzeit",
        location: "London, UK",
        description: "Grundschulzeit im Vereinigten Königreich.",
        tags: [],
        type: "education",
      },
      {
        id: "grundschule",
        year: 2007,
        period: "2007 – 2010",
        title: "Grundschule St. Wolfgang",
        org: "Grundschulzeit",
        location: "Landshut",
        description: "Beginn der Schulzeit in Landshut.",
        tags: [],
        type: "education",
      },
    ],
  },
  projects: {
    heading: "Projekte",
    sub: "Woran ich in der Forschungsgruppe Applied Education Technologies baue und mitwirke.",
    statusLabels: { ongoing: "Laufend", past: "Abgeschlossen" },
    items: [
      {
        id: "tumapply",
        name: "TUMApply",
        status: "ongoing",
        flagship: true,
        role: "Agile Coach · SysAdmin · Entwickler",
        description:
          "Ein inklusives und effizientes Bewerbungsportal für Promotionsstellen an der TUM. Ich leite den agilen Prozess für 6 Entwickler, betreibe die Serverinfrastruktur, entwickle mit und betreue Bachelorarbeiten rund um die Plattform.",
        tags: ["Java", "Spring Boot", "Angular", "Agile", "Docker", "CI/CD", "GitHub"],
        link: "https://aet.cit.tum.de/projects/edtech/tum-apply/",
      },
      {
        id: "nexus",
        name: "Project Nexus",
        status: "ongoing",
        role: "Masterarbeit · Visualisierung",
        description:
          "KI-gestütztes Technologie-Foresight-System, entwickelt als meine Masterarbeit in Zusammenarbeit mit BMW: Trendsignale werden zu wahrscheinlichkeitsgewichteten Zukunftsszenarien, präsentiert als interaktives „Fenster in die Zukunft“ auf dem Touch-Display des BMW Future Lab. Ich verantworte die interaktive Visualisierung vollständig.",
        tags: ["AI", "Technology Foresight", "Data Visualization", "Touch UI", "React", "Python", "DevOps", "Docker", "CI/CD", "GitHub"],
        link: "[PLACEHOLDER: Project Nexus link]",
      },
      {
        id: "artemis",
        name: "Artemis",
        status: "ongoing",
        role: "Reviewer · Contributor",
        description:
          "Interaktive Lernplattform mit tausenden Studierenden. Entwickler während meiner Bachelorarbeit, heute Reviewer mit gelegentlichen Pull Requests.",
        tags: ["Java", "Spring Boot", "Angular", "Docker", "CI/CD", "GitHub"],
        link: "https://github.com/ls1intum/Artemis",
      },
      {
        id: "tumi",
        name: "TUMi Chatbot",
        status: "ongoing",
        role: "Qualitätssicherung",
        description: "Chatbot für die TUM — ich verantworte die Qualitätssicherung.",
        tags: ["LLM", "QA", "Docker", "CI/CD", "GitHub"],
        link: "https://aet.cit.tum.de/projects/courses/ipraktikum/25s/",
      },
      {
        id: "athena",
        name: "Athena",
        status: "past",
        role: "Entwickler",
        description:
          "KI-gestütztes Bewertungssystem. Ich habe das Code-Quality-Assessment für Programmieraufgaben entwickelt.",
        tags: ["Python", "LLM", "LangChain", "Docker", "CI/CD", "GitHub"],
        link: "https://aet.cit.tum.de/projects/edtech/athena/",
      },
      {
        id: "ares",
        name: "Ares",
        status: "past",
        role: "Entwickler",
        description:
          "Sichere Testausführung für Programmieraufgaben, umgesetzt mit AspectJ und aspektorientierter Programmierung.",
        tags: ["Java", "AspectJ", "Docker", "CI/CD", "GitHub"],
        link: "https://aet.cit.tum.de/projects/se/ares/",
      },
      {
        id: "harmonia",
        name: "Harmonia",
        status: "past",
        role: "Entwickler",
        description:
          "LLM-gestützte Bewertung von Zusammenarbeit und Codequalität für teambasierte Programmierkurse, im Team entwickelt.",
        tags: ["Java", "Spring Boot", "Spring AI", "React", "Docker", "CI/CD", "GitHub"],
        link: "https://github.com/ls1intum/Harmonia",
      },
    ],
  },
  teaching: {
    heading: "Lehre & Mentoring",
    coursesHeading: "Kurse",
    courses: [
      {
        semester: "Sommer 2026",
        name: "DevOps: Engineering for Deployment and Operations",
        link: "https://aet.cit.tum.de/teaching/26s/devops/",
      },
      {
        semester: "Winter 2025/26",
        name: "Einführung in die Programmierung",
        link: "https://aet.cit.tum.de/teaching/25w/itp/",
      },
      {
        semester: "Winter 2025/26",
        name: "Patterns in Software Engineering",
        link: "https://aet.cit.tum.de/teaching/25w/pse/",
      },
      {
        semester: "Winter 2025/26",
        name: "Praktikum: Interactive Learning",
        link: "https://aet.cit.tum.de/teaching/25w/interactive-learning-practical/",
      },
      {
        semester: "Sommer 2025",
        name: "DevOps: Engineering for Deployment and Operations",
        link: "https://aet.cit.tum.de/teaching/25s/devops/",
      },
      {
        semester: "Winter 2024/25",
        name: "Einführung in die Programmierung",
        link: "https://aet.cit.tum.de/teaching/24w/itp/",
      },
      {
        semester: "Winter 2023/24",
        name: "Einführung in die Programmierung",
        link: "https://aet.cit.tum.de/teaching/23w/itp/",
      },
      {
        semester: "Sommer 2022",
        name: "Einführung in die Softwaretechnik",
        link: "https://aet.cit.tum.de/teaching/22s/eist/",
      },
    ],
    thesesHeading: "Betreute Abschlussarbeiten",
    thesisStatusLabels: { "in-progress": "Laufend", finished: "Abgeschlossen" },
    theses: [
      {
        year: 2026,
        title: "Integrating AI Assistance in TUM's Doctoral Application Portal",
        student: "Catherine Kalra",
        status: "in-progress",
        link: "https://aet.cit.tum.de/theses/integrating-ai-assistance-in-tums-doctoral-application-portal/",
      },
      {
        year: 2026,
        title:
          "Integrating AI-Assisted Job Advertisement Creation and Compliance Checking in TUMApply",
        student: "Melissa Sioukri Oglou",
        status: "in-progress",
        link: "https://aet.cit.tum.de/theses/integrating-ai-assisted-job-advertisement-creation-and-compliance-checking-in-tumapply/",
      },
      {
        year: 2026,
        title:
          "Enhancing Notifications and Profile Management in TUM's Doctoral Application Portal",
        student: "Celine Lahnor",
        status: "in-progress",
        link: "https://aet.cit.tum.de/theses/enhancing-notifications-and-profile-management-in-tums-doctoral-application-portal/",
      },
      {
        year: 2025,
        title:
          "Development of an Appointment Scheduler for the TUM Doctoral Application Portal",
        student: "Abinaya Anita Sivaguru",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/development-of-an-appointment-scheduler-for-the-tum-doctoral-application-portal/",
      },
      {
        year: 2025,
        title:
          "Development of Administrative Tools and Privacy Compliance for the TUM Doctoral Application Portal",
        student: "Sehmuel Wagner",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/development-of-administrative-tools-and-privacy-compliance-for-the-tum-doctoral-application-portal/",
      },
      {
        year: 2025,
        title: "Improving Usability and Inclusivity in TUM's Doctoral Application Portal",
        student: "Kiara Pia Copony",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/improving-usability-and-inclusivity-in-tums-doctoral-application-portal/",
      },
      {
        year: 2025,
        title:
          "A Modular Review and Notification System for the Doctoral Application Portal at TUM",
        student: "Moritz Schmidt",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/a-modular-review-and-notification-system-for-the-doctoral-application-portal-at-tum/",
      },
      {
        year: 2025,
        title:
          "Development of a User-Centric Application Management Module for the TUM Doctoral Portal",
        student: "Sarah Douglas",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/development-of-a-user-centric-application-management-module-for-the-tum-doctoral-portal/",
      },
      {
        year: 2025,
        title:
          "Development of a Job Management Interface for an Inclusive and Efficient Doctoral Application Portal at TUM",
        student: "Ishani Budhwar",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/development-of-a-job-management-interface-for-an-inclusive-and-efficient-doctoral-application-portal-at-tum/",
      },
    ],
  },
  contact: {
    heading: "Lass uns connecten",
    body: "Ob Recruiter oder einfach neugierig — meine Inbox ist offen.",
    emailCta: "Schreib mir",
  },
}
