import type { Content } from "./types"

export const en: Content = {
  nav: {
    home: "Home",
    about: "About",
    experience: "Experience",
    projects: "Projects",
    teaching: "Teaching",
    contact: "Contact",
  },
  hero: {
    eyebrow: "Software Engineer · Agile Coach",
    name: "Aniruddh Zaveri",
    tagline:
      "I teach Software Engineering and DevOps at TUM and like working with LLMs, EdTech and data-driven systems.",
    workProfileCta: "Work Profile",
    statusBadge: "M.Sc. Information Systems @ TUM",
  },
  about: {
    heading: "About Me",
    body: "I'm an Information Systems student at the Technical University of Munich and a software engineer at the Applied Education Technologies research group. I lead the agile process behind TUMApply, supervised bachelor's theses and teach courses from Introduction to Programming to DevOps. I love the intersection between management and informatics. In my free time you'll find me playing team sports like hockey, or gaming.",
    interestsHeading: "Interests",
    interests: [
      "LLMs & AI applications",
      "Educational technology",
      "Data-driven systems",
      "Automotive industry",
      "Agile project management",
    ],
    languagesHeading: "Languages",
    languages: [
      { name: "German", level: "Native" },
      { name: "English", level: "Native" },
      { name: "Hindi", level: "Expert" },
      { name: "French", level: "Beginner" },
    ],
  },
  skills: {
    heading: "Tech I work with",
    items: [
      "Java",
      "TypeScript",
      "Angular",
      "React",
      "Python",
      "Spring Boot",
      "Spring AI",
      "LangChain",
      "SQL",
      "Docker",
      "CI/CD",
      "AspectJ",
      "Git & GitHub",
      "Agile / Scrum",
      "Software Architecture",
    ],
  },
  experience: {
    heading: "Experience",
    sub: "My journey so far — newest first.",
    typeLabels: { work: "Work", education: "Education" },
    entries: [
      {
        id: "nexus-thesis",
        year: 2026,
        period: "Jun 2026 – Dec 2026",
        title: "Master's Thesis — Project Nexus",
        org: "Technical University of Munich · BMW",
        location: "Munich",
        description:
          "AI-driven technology foresight system in cooperation with BMW: trend signals become probability-weighted future scenarios. Fully responsible for the interactive visualization on the BMW Future Lab touch display.",
        tags: ["AI", "Data Visualization", "Touch UI", "React", "Python", "DevOps"],
        type: "education",
      },
      {
        id: "tum-pm",
        year: 2025,
        period: "Feb 2025 – Present",
        title: "Project Management & System Administration",
        org: "TU München · Applied Education Technologies",
        location: "Munich",
        description:
          "Digitalizing TUM's doctoral hiring process with TUMApply. Agile Coach for a team of 6 developers, server administration, hands-on development and supervision of bachelor's theses.",
        tags: ["Agile", "Java", "Angular", "Server Admin", "DevOps", "Mentoring"],
        type: "work",
      },
      {
        id: "msc",
        year: 2025,
        period: "2025 – 2027 (expected)",
        title: "M.Sc. Information Systems",
        org: "TU München",
        description:
          "Master's studies focusing on the intersection of software engineering, data and business.",
        tags: [],
        type: "education",
      },
      {
        id: "tum-tutor",
        year: 2024,
        period: "Feb 2024 – Sep 2026 (expected)",
        title: "Tutor & Instructor",
        org: "TU München",
        description:
          "Tutor for Introduction to Software Engineering, Introduction to Programming, DevOps and Patterns in Software Engineering.",
        tags: ["Teaching", "Java", "DevOps"],
        type: "work",
      },
      {
        id: "bcg",
        year: 2022,
        period: "Mar 2022 – Feb 2024",
        title: "IT Working Student",
        org: "Boston Consulting Group",
        location: "Munich",
        description:
          "IT service management, process optimization, IT trainings and support, conference talks, programming and agile ways of working.",
        tags: ["ITSM", "Process Optimization", "Trainings"],
        type: "work",
      },
      {
        id: "ise",
        year: 2022,
        period: "Apr 2022 – Aug 2022",
        title: "Instructor — Introduction to Software Engineering",
        org: "TU München",
        description:
          "Lecture support, exercise creation, tutorial group coordination and exam assistance.",
        tags: ["Teaching"],
        type: "work",
      },
      {
        id: "bsc",
        year: 2020,
        period: "2020 – 2025",
        title: "B.Sc. Information Systems",
        org: "TU München",
        description:
          "Bachelor's thesis: Visualization of Test Case Errors — Enhancing Autograding Feedback (developed in Artemis).",
        tags: [],
        type: "education",
      },
      {
        id: "head-tutor",
        year: 2020,
        period: "Oct 2020 – Feb 2021",
        title: "Head Tutor — Introduction to Programming",
        org: "TU München",
        description:
          "Coordinated tutors and supported students in one of TUM's biggest programming courses.",
        tags: ["Teaching"],
        type: "work",
      },
      {
        id: "telis",
        year: 2020,
        period: "Aug 2020 – Dec 2020",
        title: "Consulting / Financial Analysis",
        org: "TELIS FINANZ AG",
        description:
          "Worked as a financial consultant after completing a short training for the role.",
        tags: ["Consulting"],
        type: "work",
      },
      {
        id: "bmw",
        year: 2017,
        period: "Sep 2017 – Oct 2017",
        title: "Student Internship — International Accounting",
        org: "BMW Group",
        location: "Munich",
        description:
          "Part of the International Accounting department (FR-25), gaining insights into the finance processes of a global automotive group.",
        tags: ["Finance"],
        type: "work",
      },
      {
        id: "abitur",
        year: 2012,
        period: "2012 – 2020",
        title: "Hans-Leinberger-Gymnasium",
        org: "Abitur",
        location: "Landshut",
        description:
          "Allgemeine Hochschulreife in 2020 and the Mittlere Reife (intermediate certificate) in 2018.",
        tags: [],
        type: "education",
      },
      {
        id: "colham",
        year: 2010,
        period: "2010 – 2012",
        title: "Colham Manor Primary School",
        org: "Primary education",
        location: "London, UK",
        description: "Primary education in the United Kingdom.",
        tags: [],
        type: "education",
      },
      {
        id: "grundschule",
        year: 2007,
        period: "2007 – 2010",
        title: "Grundschule St. Wolfgang",
        org: "Primary education",
        location: "Landshut",
        description: "Start of primary education in Landshut.",
        tags: [],
        type: "education",
      },
    ],
  },
  projects: {
    heading: "Projects",
    sub: "Things I build, maintain and care about at the Applied Education Technologies group.",
    statusLabels: { ongoing: "Ongoing", past: "Past" },
    items: [
      {
        id: "tumapply",
        name: "TUMApply",
        status: "ongoing",
        flagship: true,
        role: "Agile Coach · SysAdmin · Developer",
        description:
          "An inclusive and efficient doctoral application portal for TUM. I lead the agile process for 6 developers, run the server infrastructure, contribute code and supervise bachelor's theses around the platform.",
        tags: ["Java", "Spring Boot", "Angular", "Agile", "Docker", "CI/CD", "GitHub"],
        link: "https://aet.cit.tum.de/projects/edtech/tum-apply/",
      },
      {
        id: "nexus",
        name: "Project Nexus",
        status: "ongoing",
        role: "Master's Thesis · Visualization",
        description:
          "AI-driven technology foresight system, developed as my Master's thesis in cooperation with BMW: trend signals become probability-weighted future scenarios, presented as an interactive \"window into the future\" on the BMW Future Lab touch display. I am fully responsible for the interactive visualization.",
        tags: ["AI", "Technology Foresight", "Data Visualization", "Touch UI", "React", "Python", "DevOps", "Docker", "CI/CD", "GitHub"],
        link: "[PLACEHOLDER: Project Nexus link]",
      },
      {
        id: "artemis",
        name: "Artemis",
        status: "ongoing",
        role: "Reviewer · Contributor",
        description:
          "Interactive learning platform used by thousands of students. Developer during my bachelor's thesis, now contributing as reviewer and with occasional pull requests.",
        tags: ["Java", "Spring Boot", "Angular", "Docker", "CI/CD", "GitHub"],
        link: "https://github.com/ls1intum/Artemis",
      },
      {
        id: "tumi",
        name: "TUMi Chatbot",
        status: "ongoing",
        role: "Quality Assurance",
        description: "Chatbot for TUM — I take care of quality assurance.",
        tags: ["LLM", "QA", "Docker", "CI/CD", "GitHub"],
        link: "https://aet.cit.tum.de/projects/courses/ipraktikum/25s/",
      },
      {
        id: "athena",
        name: "Athena",
        status: "past",
        role: "Developer",
        description:
          "AI-powered assessment system. I developed the programming exercise code quality assessment feature.",
        tags: ["Python", "LLM", "LangChain", "Docker", "CI/CD", "GitHub"],
        link: "https://aet.cit.tum.de/projects/edtech/athena/",
      },
      {
        id: "ares",
        name: "Ares",
        status: "past",
        role: "Developer",
        description:
          "Secure test execution for programming exercises, built with AspectJ and aspect-oriented programming.",
        tags: ["Java", "AspectJ", "Docker", "CI/CD", "GitHub"],
        link: "https://aet.cit.tum.de/projects/se/ares/",
      },
      {
        id: "harmonia",
        name: "Harmonia",
        status: "past",
        role: "Developer",
        description:
          "LLM-driven collaboration assessment and code quality feedback for team-based programming courses, developed as part of a team.",
        tags: ["Java", "Spring Boot", "Spring AI", "React", "Docker", "CI/CD", "GitHub"],
        link: "https://github.com/ls1intum/Harmonia",
      },
    ],
  },
  teaching: {
    heading: "Teaching & Mentoring",
    coursesHeading: "Courses",
    courses: [
      {
        semester: "Summer 2026",
        name: "DevOps: Engineering for Deployment and Operations",
        link: "https://aet.cit.tum.de/teaching/26s/devops/",
      },
      {
        semester: "Winter 2025/26",
        name: "Introduction to Programming",
        link: "https://aet.cit.tum.de/teaching/25w/itp/",
      },
      {
        semester: "Winter 2025/26",
        name: "Patterns in Software Engineering",
        link: "https://aet.cit.tum.de/teaching/25w/pse/",
      },
      {
        semester: "Winter 2025/26",
        name: "Practical Course: Interactive Learning",
        link: "https://aet.cit.tum.de/teaching/25w/interactive-learning-practical/",
      },
      {
        semester: "Summer 2025",
        name: "DevOps: Engineering for Deployment and Operations",
        link: "https://aet.cit.tum.de/teaching/25s/devops/",
      },
      {
        semester: "Summer 2025",
        name: "Introduction to Software Engineering",
        link: "https://dse.in.tum.de/teaching/eist-25/",
      },
      {
        semester: "Winter 2024/25",
        name: "Introduction to Programming",
        link: "https://aet.cit.tum.de/teaching/24w/itp/",
      },
      {
        semester: "Summer 2024",
        name: "Introduction to Software Engineering",
        link: "https://dse.in.tum.de/teaching/eist-24/",
      },
      {
        semester: "Winter 2023/24",
        name: "Introduction to Programming",
        link: "https://aet.cit.tum.de/teaching/23w/itp/",
      },
      {
        semester: "Summer 2023",
        name: "Introduction to Software Engineering",
        link: "https://dse.in.tum.de/teaching/ss23-eist23/",
      },
      {
        semester: "Summer 2022",
        name: "Introduction to Software Engineering",
        link: "https://aet.cit.tum.de/teaching/22s/eist/",
      },
    ],
    thesesHeading: "Supervised Theses",
    thesisStatusLabels: { "in-progress": "In progress", finished: "Finished" },
    theses: [
      {
        year: 2026,
        title: "Integrating AI Assistance in TUM's Doctoral Application Portal",
        student: "Catherine Kalra",
        status: "in-progress",
        link: "https://aet.cit.tum.de/theses/integrating-ai-assistance-in-tums-doctoral-application-portal/",
      },
      {
        year: 2026,
        title:
          "Integrating AI-Assisted Job Advertisement Creation and Compliance Checking in TUMApply",
        student: "Melissa Sioukri Oglou",
        status: "in-progress",
        link: "https://aet.cit.tum.de/theses/integrating-ai-assisted-job-advertisement-creation-and-compliance-checking-in-tumapply/",
      },
      {
        year: 2026,
        title:
          "Enhancing Notifications and Profile Management in TUM's Doctoral Application Portal",
        student: "Celine Lahnor",
        status: "in-progress",
        link: "https://aet.cit.tum.de/theses/enhancing-notifications-and-profile-management-in-tums-doctoral-application-portal/",
      },
      {
        year: 2025,
        title:
          "Development of an Appointment Scheduler for the TUM Doctoral Application Portal",
        student: "Abinaya Anita Sivaguru",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/development-of-an-appointment-scheduler-for-the-tum-doctoral-application-portal/",
      },
      {
        year: 2025,
        title:
          "Development of Administrative Tools and Privacy Compliance for the TUM Doctoral Application Portal",
        student: "Sehmuel Wagner",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/development-of-administrative-tools-and-privacy-compliance-for-the-tum-doctoral-application-portal/",
      },
      {
        year: 2025,
        title: "Improving Usability and Inclusivity in TUM's Doctoral Application Portal",
        student: "Kiara Pia Copony",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/improving-usability-and-inclusivity-in-tums-doctoral-application-portal/",
      },
      {
        year: 2025,
        title:
          "A Modular Review and Notification System for the Doctoral Application Portal at TUM",
        student: "Moritz Schmidt",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/a-modular-review-and-notification-system-for-the-doctoral-application-portal-at-tum/",
      },
      {
        year: 2025,
        title:
          "Development of a User-Centric Application Management Module for the TUM Doctoral Portal",
        student: "Sarah Douglas",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/development-of-a-user-centric-application-management-module-for-the-tum-doctoral-portal/",
      },
      {
        year: 2025,
        title:
          "Development of a Job Management Interface for an Inclusive and Efficient Doctoral Application Portal at TUM",
        student: "Ishani Budhwar",
        status: "finished",
        link: "https://aet.cit.tum.de/theses/development-of-a-job-management-interface-for-an-inclusive-and-efficient-doctoral-application-portal-at-tum/",
      },
    ],
  },
  contact: {
    heading: "Let's connect",
    body: "Whether you're a recruiter or just curious — my inbox is open.",
    emailCta: "Say hello",
  },
}
